# -*- coding: utf-8 -*-
"""Exercicio_modulo_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wFLyR6QmrIv8UenCXt10Q1uBZ5RwQ2cw
"""

def multiplo(numero):

  if ((resto_de_5) == 0) and ((resto_de_7) == 0):
    print('fizzbuzz')
  else:
    if ((resto_de_5) == 0):
      print('fizz')
    else:
      if ((resto_de_7) == 0):
        print('buzz')
      else:
        print('miss')

import pytest

import sys
sys.path.append('tarefa_modulo_1')

numero = int(input('Digite um número:'))

resto_de_5 = numero % 5
resto_de_7 = numero % 7

class TesteMultiplo:
  def setup(self):
    pass

  def test_multiplo(self):
    assert numero == 35

multiplo(35)

#!pip install pycodestyle

!python -m pycodestyle armenioca/Modulo_5/Exercicio_modulo_5.py